services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: alertsdb
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./AlertaComunidade/target/alerta-comunidade-0.0.1-SNAPSHOT.jar:/app/alerta-comunidade-0.0.1-SNAPSHOT.jar
    ports:
      - "8080:8080"
    depends_on:
      - db
      - rabbitmq

volumes:
  db_data:
