server:
  port: 8081

spring:
  application:
    name: persistence-consumer

  datasource:
    url: jdbc:mariadb://db:3306/alertsdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    url: jdbc:mysql://db:3306/alertsdb
    user: root
    password: root
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always
