server:
  port: 8080

spring:
  application:
    name: alerta-comunidade
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false



# Habilita o Swagger UI do Springdoc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always




