server:
  port: 8080

spring:
  application:
    name: alerta-comunidade

  datasource:
    url: ${DB_URL:jdbc:mariadb://db:3306/alertsdb}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  flyway:
    enabled: true
    url: ${FLYWAY_URL:jdbc:mysql://db:3306/alertsdb}
    user: ${FLYWAY_USER:root}
    password: ${FLYWAY_PASSWORD:root}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  mail:
    host: ${MAIL_HOST:smtp}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:user}
    password: ${MAIL_PASSWORD:pass}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  from-number: ${TWILIO_FROM_NUMBER}



# Converte camelCase -> snake_case no banco de dados (opcional)
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Habilita o Swagger UI do Springdoc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  endpoint:
    health:
      show-details: always




