server:
  port: 8080

spring:
  application:
    name: alerta-comunidade

  datasource:
    url: jdbc:mariadb://db:3306/alertsdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # cria ou atualiza o schema automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

# Converte camelCase -> snake_case no banco de dados (opcional)
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Habilita o Swagger UI do Springdoc
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
