server:
  port: 8082

spring:
  application:
    name: failed-management
  datasource:
    url: jdbc:mariadb://db:3306/alertsdb
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MariaDBDialect
